import { ValidationError } from "@distribution/core";

/** Storage keys are relative, forward-slash paths under a small set of
 *  prefixes. They are generated by the server, never taken from the client,
 *  and validated again on read so a bad row can never escape the root. */
export const ALLOWED_PREFIXES = ["products/", "projects/", "promo/", "references/", "uploads/", "tmp/"] as const;

const SAFE_SEGMENT = /^[A-Za-z0-9._-]+$/;

export function assertValidKey(key: string): string {
  if (!key || key.length > 512) throw new ValidationError("storage key length", { key });
  if (!ALLOWED_PREFIXES.some((p) => key.startsWith(p))) throw new ValidationError("storage key prefix", { key });
  const parts = key.split("/");
  for (const part of parts) {
    if (part === "" || part === "." || part === "..") throw new ValidationError("storage key segment", { key });
    if (!SAFE_SEGMENT.test(part)) throw new ValidationError("storage key characters", { key });
  }
  return key;
}

export const keys = {
  sourceOriginal: (productId: string, sourceId: string, ext: string) =>
    `products/${productId}/sources/${sourceId}/original.${ext}`,
  sourceAudio: (productId: string, sourceId: string) => `products/${productId}/sources/${sourceId}/audio-16k.wav`,
  transcript: (productId: string, sourceId: string, transcriptId: string) =>
    `products/${productId}/sources/${sourceId}/transcripts/${transcriptId}.json`,
  brandAsset: (productId: string, assetId: string, ext: string) => `products/${productId}/brand/${assetId}.${ext}`,
  clip: (projectId: string, candidateId: string, stage: string) => `projects/${projectId}/clips/${candidateId}/${stage}.mp4`,
  clipArtifact: (projectId: string, candidateId: string, name: string) =>
    `projects/${projectId}/clips/${candidateId}/${name}`,
  thumbnail: (projectId: string, assetId: string) => `projects/${projectId}/thumbnails/${assetId}.png`,
  promo: (projectId: string, rel: string) => `promo/${projectId}/${rel}`,
  reference: (referenceId: string, rel: string) => `references/${referenceId}/${rel}`,
  upload: (uploadId: string, ext: string) => `uploads/${uploadId}.${ext}`,
};
