import type { ProductProfile } from "@distribution/core";
import type { Storyboard } from "@distribution/promo-kit/schema";
import type { Structure } from "./structures";

export interface DirectionInput {
  profile: ProductProfile;
  storyboard: Storyboard;
  structure: Structure;
  notes: string[];
  reference?: { url: string; title?: string; analysisSummary?: string } | null;
  provider?: string | null;
}

/**
 * `CREATIVE_DIRECTION.md` — the same deliverable the skill produced by hand, so
 * the founder can see the reasoning rather than only the render. Sections match
 * the original: reference, product, direction, storyboard, production.
 */
export function creativeDirectionMarkdown(input: DirectionInput): string {
  const { profile, storyboard, structure, notes } = input;
  const p = profile.product;
  const palette = profile.brand.palette;
  const fps = storyboard.fps;
  const t = (frames: number) => `${(frames / fps).toFixed(1)}s`;

  const feats = [...p.features].sort((a, b) => a.priority - b.priority);

  return `# ${p.name} — creative direction

_Generated by Distribution for profile v${profile.version} on ${new Date().toISOString().slice(0, 10)}._

## 1. Reference

${
    input.reference
      ? `Reference: **${input.reference.title ?? input.reference.url}** — ${input.reference.url}\n\n${input.reference.analysisSummary ?? ""}`
      : `No reference video was supplied, so the structure was derived from the product itself rather than reverse-engineered from a film. The director used the **${structure.id}** structure.\n\n> ${structure.rationale}`
  }

## 2. The product

**${p.name}** — ${p.tagline}

${p.description ?? ""}

- **Category:** ${p.category.primary}${p.category.tags.length ? ` (${p.category.tags.join(", ")})` : ""}
- **Platforms:** ${p.platforms.join(", ")}
- **Audience:** ${p.audience.summary}
${p.audience.painPoints.length ? `- **Pain points:** ${p.audience.painPoints.join("; ")}` : ""}

Features, in the priority the founder set:

${feats.map((f, i) => `${i + 1}. **${f.title}**${f.detail ? ` — ${f.detail}` : ""}`).join("\n")}

## 3. Creative direction

| Role | Colour | Where it lands |
|---|---|---|
| Accent | \`${palette?.accent ?? "—"}\` | keywords, the score ring, the caret, card tints |
| Ink | \`${palette?.ink ?? "—"}\` | all primary type |
| Canvas | \`${palette?.canvas ?? "—"}\` | the light ground every scene sits on |
| Ground | \`${palette?.ground ?? "—"}\` | inverted scenes (typewriter, split right) |

Palette source: **${palette?.source ?? "default"}**${palette?.source === "inferred" ? " — sampled from the uploaded logo and screenshots." : ""}

Motion language is the kit's: spring-everything (nothing eases linearly), a single hero per frame, float-idle on held objects, and intentional transitions. Type is set in ${storyboard.scenes.some((s) => s.kind === "typewriter") ? "a geometric sans against a monospace system voice" : "a geometric sans"}.

## 4. Storyboard

| # | Beat | In | Duration | On screen |
|---|---|---|---|---|
${storyboard.scenes
  .map((s, i) => `| ${i + 1} | \`${s.kind}\` | ${t(s.start)} | ${t(s.duration)} | ${Object.values(s.copy).filter(Boolean).slice(0, 3).join(" · ") || "—"} |`)
  .join("\n")}

${notes.map((n) => `- ${n}`).join("\n")}

## 5. Production

- **Renders:** 1080×1920 (Reels/TikTok/Shorts), 1920×1080 (YouTube/web), 886×1920 and 1920×886 (App Store previews, trimmed to ≤30s at 30fps).
- **Audio:** ${storyboard.sfx.length} sound cues mapped to on-screen action, mixed locally over an ambient pad. No narration.
- **Duration:** ${t(storyboard.durationFrames)} at ${fps}fps.
- **Copy provenance:** every line traces to the product profile — feature titles, pain points, the tagline, the product name. Nothing was invented${input.provider ? `; written with ${input.provider}` : " by a model"}.
`;
}
